### ISSUE TITLE
[Bug]: checksum error when building OpenBumbleBee

### ISSUE THREAD

**Issue by pyz-creeper** [AntCPLab/OpenBumbleBee#1]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

current version (1f4aa6aa)

### OS Platform and Distribution

20.04

### Python Version

3.10.13

### Compiler Version

gcc 11.4.0

### Current Behavior?

When build spu, an checksum error was reported by bazel. The package name is "com_github_microsoft_seal" and the version is 4.1.2. While the checksum of the downloaded file is acc2a1a127a85d1e1ffcca3ffd148f736e665df6d6b072df0e42fff64795a13c, the sha256 provided in OpenBumbleBee/bazel/repositories.bzl is 78ef7334114de930daf7659e8ba60c5abfff85c86ec2b827a2b7c67c3c42da43. I am not sure if I should change the sha256 in the file or use another version.

### Standalone code to reproduce the issue

```Python
def _com_github_microsoft_seal():
    maybe(
        http_archive,
        name = "com_github_microsoft_seal",
        # sha256 = "78ef7334114de930daf7659e8ba60c5abfff85c86ec2b827a2b7c67c3c42da43",
        sha256 = "acc2a1a127a85d1e1ffcca3ffd148f736e665df6d6b072df0e42fff64795a13c",
        strip_prefix = "SEAL-4.1.2",
        type = "tar.gz",
        patch_args = ["-p1"],
        patches = ["@spulib//bazel:patches/seal.patch"],
        urls = [
            "https://github.com/microsoft/SEAL/archive/refs/tags/v4.1.2.tar.gz",
        ],
        build_file = "@spulib//bazel:seal.BUILD",
    )
```

**Comment by fionser** [comment]
It seems SEAL update their repo but not changing the version number :(
