### ISSUE TITLE
[Bug]: bole算法实现

### ISSUE THREAD

**Issue by xbcReal** [AntCPLab/OpenBumbleBee#5]
### Issue Type

Support

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

ndss branch

### OS Platform and Distribution

ubuntu 22.04

### Python Version

3.9

### Current Behavior?

你好，我想请问一下论文中提到得到bole算法相关的代码提交是否已经在ndss分支上了呢，看了下cheetah_mul.cc感觉是没有找到和论文中描述的算法的实现呢。麻烦解答一下，不胜感激。

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by fionser** [comment]
cheetah_mul.cc already implement the BOLE functionality. See https://github.com/AntCPLab/OpenBumbleBee/blob/ndss/libspu/mpc/cheetah/arith/cheetah_mul.h#L49

**Comment by mufengwuxi** [comment]
Hello, I would like to ask where the lift function is reflected in the MulOLE in cheetah_mul.cc.

**Comment by fionser** [comment]
* https://github.com/AntCPLab/OpenBumbleBee/blob/ndss/libspu/mpc/cheetah/arith/cheetah_mul.cc#L588C9-L588C18
* and https://github.com/AntCPLab/OpenBumbleBee/blob/ndss/libspu/mpc/cheetah/rlwe/modswitch_helper.h#L45
