### ISSUE TITLE
[Bug]: Softmax dimensions in microbenchmark script

### ISSUE THREAD

**Issue by cora-shao** [AntCPLab/OpenBumbleBee#6]
### Issue Type

Others

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

most recent (3931bbb)

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.10

### Compiler Version

11.4.0

### Current Behavior?

Regarding the benchmark script for softmax, could you explain the reasoning/context behind the dimensions of the input matrix x to softmax?
The paper describes softmax as being applied to each row of the input 2D matrix (QK^T + M, which would be a square matrix), but the script has dimensions 128 x 32. Is it modelling the total computation across heads with H = 32? 

### Standalone code to reproduce the issue

```Python
x = np.random.randn(128, 32) * 8.0
```

**Comment by fionser** [comment]
It just simply models the softmax computation on a 128x32 matrix.
